//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDev_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public string CargoID { get; set; }
        public string CType { get; set; }
        public int HazPer { get; set; }
        public decimal WRate { get; set; }
        public decimal DRate { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
