//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDev_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        [Required]
        [DisplayName("Driver Number")]
        public string DriverNo { get; set; }
        [Required]
        [DisplayName("Driver Name")]
        public string DName { get; set; }
        [DisplayName("Driver ID Number")]
        public string DriverID { get; set; }
        [DisplayName("Driver Liscence Code")]
        public string Licen { get; set; }
        [DisplayName("Date of Employment")]
        public System.DateTime DOE { get; set; }
        [DisplayName("Adddress")]
        public string Adrs { get; set; }
        [DisplayName("Contact Number")]
        public string ConNum { get; set; }

        public string nokCNum { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
