//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDev_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string JobID { get; set; }
        public string jState { get; set; }
        public string SLoc { get; set; }
        public string STime { get; set; }
        public string ELoc { get; set; }
        public string ETA { get; set; }
        public string Dist { get; set; }
        public decimal BasicCost { get; set; }
        public string ActArrive { get; set; }
        public string CHeight { get; set; }
        public string CLength { get; set; }
        public string CWidth { get; set; }
        public string CWeight { get; set; }
        public string AbLoad { get; set; }
        public string MBefore { get; set; }
        public string MAfter { get; set; }
        public string ExpctFuel { get; set; }
        public string ActFuel { get; set; }
        public string Flag { get; set; }
        public string TruckID { get; set; }
        public string CustomerID { get; set; }
        public string CargoID { get; set; }
        public string DriverNo { get; set; }
        public string CDisc { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Truck Truck { get; set; }
    }
}
