//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDev_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public Truck()
        {
            this.ServiceHistories = new HashSet<ServiceHistory>();
            this.Jobs = new HashSet<Job>();
        }
    
        public string TruckID { get; set; }
        public string Vin { get; set; }
        public string LP { get; set; }
        public string Tstat { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Chassis { get; set; }
        public string Cabin { get; set; }
        public string Engine { get; set; }
        public string Steering { get; set; }
        public string Powert { get; set; }
        public string Torque { get; set; }
        public string GearBox { get; set; }
        public string TankCap { get; set; }
        public string Milage { get; set; }
        public string Weightt { get; set; }
        public string MaxLoad { get; set; }
        public System.DateTime PDate { get; set; }
        public System.DateTime LSD { get; set; }
        public string GarageID { get; set; }
    
        public virtual Garage Garage { get; set; }
        public virtual ICollection<ServiceHistory> ServiceHistories { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
